### PR TITLE
Parametrize regions

### PR DESCRIPTION
**Pull request by cyrlop**
Added the region as parameter in views and in the navbar form.
I removed the tests in home page.
Sorry for the docstring changes, residual mess from the merge, we avoided 99% of the damage!!!

### CODE REVIEW

**Review by kevinrue — DISMISSED** [review]
Works for me.

We should disable the button when the summoner name is blank. 

We can probably push that in a separate PR.

**Comment by cyrlop** [comment]
@kevinrue I now prevent submission of blank summoner name, you get a nice "Please fill this field" pop-up if you try to submit an empty summoner name :)

**Review by kevinrue — APPROVED** [review]
nickel!

**Review by kevinrue — APPROVED** [review]
nickel!

**Pull request merged**
